#!/bin/bash
-rwxr--r-- 1 root root 17 Jul  5 14:28 0-current_working_directory
-rwxr--r-- 1 root root 15 Jul  5 14:42 1-listit
-rwxr--r-- 1 root root 15 Jul  5 14:51 2-bring_me_home
-rwxr--r-- 1 root root 18 Jul  5 14:57 3-listfiles
-rwxr--r-- 1 root root 18 Jul  5 15:10 4-listmorefiles
-rw-r--r-- 1 root root 17 Jul  5 14:06 README.md
